### ISSUE TITLE
Notificacions

### ISSUE THREAD

**Issue by xbelanch** [xbelanch/llegir-en-xarxa#17]
Inclou tres tipus de notificacions visuals:

* **Numèriques** associades a les icones de les apps, per exemple, nombre de missatges no llegits de l'app de correu,
* Pròpies del **sistema**, és a dir, aquelles que es deriven d'una actuació associada amb l'ús del mòbil com, per exemple, la connexió a una xarxa wifi no ha estat possible.
* Pròpies de les **apps** com, per exemple, missatges de rebudes de correu nou.

**Comment by Neth** [comment]
Afegits els tres tipus de notificacions.
