### ISSUE TITLE
Tracks from Podcast App could be played infinite times

### ISSUE THREAD

**Issue by xbelanch** [xbelanch/llegir-en-xarxa#28]
Reproducció de l'incidència:

1. Entrar al Podcast App.
2. Play a qualsevol de les tracks disponibles.
3. Tornar al homescreen (s'escolta el track que s'està reproduïnt)
4. Es torna a l'app de Podcast: l'app s'inicia sense tenir present la pista vigent o actual que s'està reproduïnt.
5. Es pot clicar a play a la mateixa pista i s'escoltarien en paral·lel les dues pistes.

**Comment by Neth** [comment]
Solucionat a feature/UI.
